### ISSUE TITLE
能否给个详细的安装说明。

### ISSUE THREAD

**Issue by findmorenow** [WangYihang/PasteBin#1]

**Comment by findmorenow** [comment]
yum install docker 
yum install docker-compose
然后按要求，git cd 
docker-compose up -d
显示
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

然后
systemctl start docker

运行里面出现WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

测试系统为 centos 7.4 X64

**Comment by WangYihang** [comment]
啊 你出现这个错误可能有两个原因：
```
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
```
1. docker 命令需要以 root 身份运行
2. docker 服务可能没有启用

> 关于安装说明：
```
少了一步创建一个 data 文件夹用来存储数据（ README.md ）已经更新
```

感谢提醒

**Comment by WangYihang** [comment]
所以安装的话就把 README.md 里面的 Install 部分粘贴到终端就可以了。这其实是个非常简单的脚本，也没有后台管理，只是为了能方便得共享命令行输出结果写的，非常简陋。

**Comment by findmorenow** [comment]
docker 服务可能没有启用的原因。
谢谢了啊。 只会照葫芦画葫芦。
另外我修改了/source/index.php 里的hosts 
这样运行结果就是架设域名了。

**Comment by WangYihang** [comment]
嗯嗯，ok，那个这 issue 关闭咯
